[package]
name = "hook86_core"
version = "0.1.0"
authors = ["descawed <github@descawed.com>"]
edition = "2024"

[dependencies]
windows = { version = "0.61.1", features = ["Win32_Foundation", "Win32_System_Memory", "Win32_System_Kernel", "Win32_System_SystemServices"] }