[package]
name = "hook86_macro"
version = "0.1.0"
authors = ["descawed <github@descawed.com>"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"